
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXpNREEwTlRJME5Gb1hEVE16TURZeU56QTBOVEkwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzBqClI1UWozdVZuOHdLZjkrU0RIZWl1bzR5VkU5RHhvTGJQd1pNVUdHZXE3bjd1RURSMnkvSHlKZG53ZEk4Q09XamoKYjIzL0JIOFdxcTJSaXBjTmFuOXVNSzZCbE9PM2J3TEhnVzM2YnM0U0U5S2M0SzN1S1Q0WVhFckZPUHEwaFZhTQpibSs4SGQrTllXNUxrcWlGblJDUDk5MGlNMHZmbFRwUWpWQ2QrdWtrbUtHQVgxUjJpa1J2ZmxPWFdIUnVlWEZWClNPRmpET3h4Qi93ZTFmdFo2Vnk5VFpoci9NeTZPMzBJYWVQZ1NUQ2FKaVpYUnNucG9kMEVCd2hkdFlabEVRTHUKM1prMEZjdXFLQ1FGTHd4QVFYVzJvMzJGdU9qTlZPdHVmNnlMSjF1aG5GYkh0QjV5VWVCM1FRZ1lrNHE3Mmc2eApIK25uaWRaNlJ0YktWMVl3dGtzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDU3NaZ0gxaWNZY2tqWnB3d2hYdmdXd1VVY1pNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjYzenk5SWQxbXZtWFJ2ZktZLwp2WXU2Y3ZOUFdLNXlYdUFIakFRYmE2bUxvQVdnYUkvaFcrbThqTEhhd1EwbW9WTHFZWnVRTUcyckxZMHZwQmRnCjBiZzg4VXBBS3RhVWhBMmxXNEI2ZThQU1ZQbEhVbFVNemlWUDBReUNKNkliQ3BqWkJES0FYcGRhalRtQ0NQL3gKK2JhT2VBYjU2OS9ZaFVKcTBoK1Q0M2FvRzdUdlgwaEowS3MwOUJpVmRMT0tuQWJ3SUh6QVd3ZDZSdlJMNzdpaQpwaTdBN05tbzVSaU1kVzhFZnZ6Y0RiY3RjSlE4dTNNblJtYzFwUnFhbERrUFVlQVhsZWN3NEcxYkMxUWNoc092CjZlb3liVnFac2xhNmhNcmNiWHcwdENzSnpSdk94cEpIalhaY0NQd3Y4ZE5OTmJML1VyMm5qV2tzZkFJQllQV24KdXJVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://730bd6c0-91bb-4373-8d3f-c9d7d82628cb.ap-south-1.linodelke.net:443
  name: lke116953

users:
- name: lke116953-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzc0lqZGE1NGNnbENlcjhDUFJOTTRUZ1FXNVBiX1dMYUpHNE5sbHo4alEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4temt4NjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDUwYjQ3ZDEtMmFiZC00NzcwLTkxM2YtYzRjMWFmMGExYzExIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.U2ldxzm0BdYFX1TMe83aFwdRPpKro9ME9-nWQNdVO8pTqYrHMKW3Nafc3AzEnNBJRiPuBOciRWQfS2KL5DbsSJZJmRw-4By-kl1no9nqC9aS6GplSyO_xbJLROro3L0iAGyT4T3RqtWfgjcPPLfu28bmUECqgcULkXvpiLfoxMNrXzaR4cNrcDwtGQt8ODKC9wjqpDbsqxTH69LOL-ukrab21KssEMlaUT9Y3bE1b_O08RGBI8t6KAdUxww-tyIbuMVs8uBJbANK6uuFAzr7VWWlxir3MOeT4BkJUENvCO8rCP6scpw4yfxTPRDfGxL9MlnFAMJcuJEHPHudGyrw7A

contexts:
- context:
    cluster: lke116953
    namespace: default
    user: lke116953-admin
  name: lke116953-ctx

current-context: lke116953-ctx
